version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: postgres-db-prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - internalnet

  tic-tac-toe-back:
    build:
      context: ./TicTacToeBack/
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - internalnet

  tic-tac-toe-front:
    build:
      context: ./TicTacToeFront/
    container_name: tic-tac-toe-front-container
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - tic-tac-toe-back
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  pgdata: {}