version: '3.8'

services:
  backend-prod:
    build:
      context: ./TicTacToeBack/
      args:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    container_name: bakcend-prod
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRE_PASSWORD_PROD}

      AWS_REGION: ${AWS_REGION}
      COGNITO_ISSUER_URI: ${COGNITO_ISSUER_URI}
      COGNITO_JWK_SET_URI: ${COGNITO_JWK_SET_URI}
      COGNITO_APP_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}
      
    networks:
      - internalnet

  frontend-prod:
    build:
      context: ./TicTacToeFront/
      args:
        NODE_ENV: ${NODE_ENV:-production}
    container_name: frontend-prod
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - tic-tac-toe-back
    networks:
      - internalnet
    environment:
      - NODE_ENV=${NODE_ENV:-production}

networks:
  internalnet:
    name: internalnet
    driver: bridge
