version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: postgres-db-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    networks:
      - internalnet

  backend:
    build:
      context: ./TicTacToeBack/
      args:
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRE_PASSWORD}

      AWS_REGION: ${AWS_REGION}
      COGNITO_ISSUER_URI: ${COGNITO_ISSUER_URI}
      COGNITO_JWK_SET_URI: ${COGNITO_JWK_SET_URI}
      COGNITO_APP_CLIENT_ID: ${COGNITO_APP_CLIENT_ID}

    networks:
      - internalnet

  frontend:
    build:
      context: ./TicTacToeFront/
      args:
        configuration: development
    container_name: frontend
    ports:
      - "80:80"
    expose:
      - 80
    depends_on:
      - backend
    networks:
      - internalnet

networks:
  internalnet:
    name: internalnet
    driver: bridge

volumes:
  pgdata: {}